schema_version: 1

context:
  version: 0.7.0

package:
  name: guidellm
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/guidellm/guidellm-${{ version }}.tar.gz
  sha256: 3432e72c61995fabcb845c0a2f3831771a663255c8efbd86a9687299e1356d03

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - setuptools-git-versioning >=2.0,<3
    - packaging
    - pip
  run:
    - python >=${{ python_min }}
    - click >=8.3.0,<8.4.dev0
    - culsans >=0.10.0,<0.11.dev0
    - datasets >=4.1.0
    - eval_type_backport
    - faker
    - ftfy >=6.0.0
    - httpx <1.0.0
    - loguru
    - msgpack-python
    - numpy >=2.0.0
    - protobuf
    - pydantic >=2.11.7
    - pydantic-settings >=2.0.0
    - pyyaml >=6.0.0
    - rich
    - sanic
    - tabulate
    - transformers
    - uvloop >=0.18
    - pytorch
    - more-itertools >=10.8.0
    - typing_extensions >=4.15.0
    - websockets >=13.0
tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - '*'
      imports:
        - guidellm
      pip_check: true

about:
  summary: Guidance platform for deploying and managing large language models.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/guidellm/

extra:
  recipe-maintainers:
    - xhochy
